In [13]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
import pickle
from sklearn.model_selection import train_test_split
import xgboost

##read data
data = pd.read_csv(r'Data\preprocessed_data.csv')

## split
x_data = data["text"][pd.isna(data["text"])==False]
y_data = data["target"][pd.isna(data["text"])== False]

##bag of word
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.95, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(x_data).toarray()
print(X)
## save vectorizer
with open("Saved/countVectorizer.pkl", 'wb') as fout:
    pickle.dump((vectorizer), fout)

##split for train and test
x_train, x_test, y_train, y_test = train_test_split(X, y_data, test_size=0.2, random_state=32)

## train
model = xgboost.XGBClassifier(n_estimators=200 ,n_jobs=6,max_depth=20, tree_method='gpu_hist') #the best
model.fit(x_train, y_train )

## test
print("score : ", model.score(x_test, y_test))

model.save_model("Saved/xgboost_bestModel.json")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\serda\Anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:46:54] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
score :  0.8289191348066471
